name: Create AWS stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        type: string

run-name: Create ${{ inputs.environment }} environment

jobs:
  create-stack:
    name: Create stack
    runs-on: ubuntu-latest
    steps:
      - name: Cache AWS CLI
        id: cache-aws-cli
        uses: actions/cache@v3
        with:
          path: |
            awscliv2.zip
            aws
          key: ${{ runner.os }}-aws-cli

      - name: Download AWS CLI
        if: steps.cache-aws-cli.outputs.cache-hit != 'true'
        run: |
          echo "----Get aws cli----"
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          echo "----Unzip----"
          unzip -q awscliv2.zip

      - name: Install AWS CLI
        run: |
          echo "----Install----"
          sudo ./aws/install --update 
          echo "----Check aws----"
          aws --version

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-3

      - name: Configure stack name
        id: stack-name
        run: |
          STACK_NAME="cars-fe-${{ inputs.environment }}"
          echo "Stack name: $STACK_NAME"
          echo "stackName=$STACK_NAME" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload CloudFormation template to S3
        run: |
          echo "----Sync template file to S3 bucket----"
          aws s3 cp ./template.cfn.yaml s3://cars-deployment/frontend/template.cfn.yaml

      - name: Deploy stack
        run: >
          if ! aws cloudformation describe-stacks 
          --stack-name ${{ steps.stack-name.outputs.stackName }}; then

          aws cloudformation create-stack 
          --stack-name ${{ steps.stack-name.outputs.stackName }}
          --template-url https://cars-deployment.s3.eu-west-3.amazonaws.com/frontend/template.cfn.yaml
          --parameters ParameterKey=Env,ParameterValue=${{ inputs.environment }}

          else

          aws cloudformation update-stack 
          --stack-name ${{ steps.stack-name.outputs.stackName }}
          --template-url https://cars-deployment.s3.eu-west-3.amazonaws.com/frontend/template.cfn.yaml
          --parameters ParameterKey=Env,ParameterValue=${{ inputs.environment }}

          fi